### ISSUE TITLE
You are +1

### ISSUE THREAD

**Issue by AnaRobynn** [P1xt/games-development-signup#1]
I just wanted to hop in to say this is an awesome idea! :)
You are doing amazing work as usual!

**Comment by P1xt** [comment]
Hey there @AnaRobynn - quick question for when I start setting everything up: Are you looking to participate? :smile:

**Comment by AnaRobynn** [comment]
Hey @P1xt! 

Most likely not since I have decided it will work better for me if I stick to my own plan. In 3y max, I want to finish OSSU with some extra courses about physics. I will give myself 2y after that to really dive into game development. 

If I'm too bored, I will pause OSSU for a while see if I can make something with Phaser. I have honestly never heard about a Typescript game engine so that's going to be cool.

However, I'll keep eye out on this repo. Awesome initiative though, but I want to stick with a plan for once. I always keep changing them😅
