### ISSUE TITLE
Just the beginning! 

### ISSUE THREAD

**Issue by razzlepdx** [P1xt/games-development-signup#10]
## Who I Am
Hi all!  I'm Rachel, a former ESL instructor, curriculum designer, and new hire trainer in healthcare.  Currently I'm studying programming full-time - I was going the self-study route and then ended up with a scholarship to Hackbright Academy in San Francisco.  I'll be done with their software engineering program in 3 weeks - just in time to jump in on something new :)  I live in the PNW.

## Where I'm At, and Where I'm Going
In 2017 I gained an intermediate understanding of python, got a solid intro to Java, and can write some crappy Javascript.  I read 4 of the YDKJS books and got through week 3 (I think) of CS50.  That was a long time ago!

Like @kvie, my plan for the month of March is to quickly review the parts of CS50 I've already done and make as much new progress in the course as I can. I also want to finish up YDKJS, and brush up on math so I'll be ready to go.

## My Commitments & Limitations
I can commit to a minimum of 10 hours a week to this group over the next two years. My goal will be about 15 hours per week.  I cannot fully express how much this plan appeals to me!  Thanks to @p1xt for coming up with this idea!

#### Areas of Interest
My interests lie mostly in back-end development, but I like pushing myself to improve on my weaknesses.  I enjoy video and table-top games and care deeply about user experience.  Might be the training background talking, but I'm also really concerned with making well-documented, fully-tested products.  

#### I enjoy Collaboration
I'm a team player, and I like to make sure that others feel comfortable and supported.  Pair programming is one of my favorite things - I always come away from it having learned something.  

#### Final Words
I'm excited to get started on this journey with you all - I look forward to learning and building great things together!

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
