### ISSUE TITLE
Signup - fiftyfivebells

### ISSUE THREAD

**Issue by fiftyfivebells** [P1xt/games-development-signup#11]
## Who I Am

Hello! My name is Stephen, and I'm a 33-year-old health inspector who's getting tired of fighting with landlords and restaurant owners. I've been an avid video game lover since I was 6 years old playing Megaman and Legend of Zelda on Nintendo, and have always thought making games would be exciting. This seems like such a great idea, and I figured why not jump in and give it my best shot with all of you!

## Where I'm At and Where I'm Going

I've been working my way through the comprehensive CS/WD guide since it was created in December 2016. Right now, I'm reading through The C Programming Language, Vol. 2 and working through Build Your Own Lisp, just because I wanted to have a better understanding of C and a lower-level language.

For this month, once I finish the two C books, I'll give Functional Light JavaScript a read through and continue brushing up on my math. A little further down the line, there's a possibility that I'll start full-time at a CS program in the fall, but that's shaky and uncertain right now.

## My Commitments and Limitations

At the moment, I'm employed full-time, but I can commit to working on things during any free time I have. I should usually be good for at least 10 hours or so a week, but some weeks it could be more or less. That said, I have a decent amount of discipline and know how to use my time efficiently.

### Areas of Interest

One thing that I've always thought would be awesome is designing enemy AI that adapts to the player. Imagine a boss in a Dark Souls-like game that would change its strategy based on how you approached it. Turtling with the shield up? The boss is going to get super aggressive to burn down your stamina! But more than that, it would be awesome if the enemy could learn over several attempts. For example, if you're always going to the left, the AI would eventually take actions to prevent it.

Plus, I've been playing all genres of games for almost 30 years. I suppose you don't need to play games to be a games developer, but I think having a good background in video games in general can only be beneficial when considering what to bring to your own games.

### Communication

In my job, I communicate with a wide variety of people on a daily basis. I think I do a very good job explaining concepts and understanding what people are trying to say. This means that I can keep people on the same page by ensuring everyone understands each other.

### Cooperation and Assisting Others

I do a lot of collaboration in my day to day life, communicating with other departments, private citizens, business-owners, etc., so I have a decent amount of experience cooperating with others to accomplish goals. I also very much enjoy helping people when I can, or working together to figure something out if I can't help directly.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
