### ISSUE TITLE
My Signup!

### ISSUE THREAD

**Issue by Zenrer** [P1xt/games-development-signup#12]
# Who I am
My name is Ryan, but I usually go by Zenrer on the internet. Currently studying an Engineering/Science double degree, but only studying part time at the moment. I'm 22 years old and been playing games for around a decade, but never taken it upon myself to understand the process behind developing a game, even though I have partially taught myself how to program. 
# Where I am, where I want to be
Recently started the CS50 course and loving it. Before that, I have taken some courses related to data science and machine learning, which is an area that I've recently taken an interest in. I'm planning on finishing CS50 by the end of the month, and will most likely jump into the YDKJS books in the mean time. 
# Commitments to you and myself
Right now, I'm committing around 20-25 hours a week to university related work, as well as working around 20-25 hours per week. Due to this,  I can commit a minimum of 10 hours a week to this project, and hopefully I can push that up to 20 hours a week on a consistent basis. 
# What I can bring
I've always had a great interest in artificial intelligence, especially in gaming. My passion for AI is what is currently driving me to learn about machine learning, and I'm sure it will help me further myself in terms of studying and developing AI in the context of game development. I'm also a great team player and leader, as these traits are required in some of the work I do outside of university. 
# My goals
To further myself in the context of game development, especially in the area of game development and design processes. This will also lead me to motivate myself to learn different areas of game development, and specifically, artificial intelligence.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
