### ISSUE TITLE
QA guy looking to partake

### ISSUE THREAD

**Issue by najdhil86** [P1xt/games-development-signup#13]
## **Who I am**

Hi everyone! My name is Navjot "Naj" Dhillon. I go by Naj. I'm Quality Assurance Tester at gaming company called, Crowdstar. I have worked in the gaming industry since the beginning of my career. Honestly, I never thought I would end up doing I'm doing, because I majored in Kinesiology (study of human movement). I'm 30 year old individual who is looking to improve himself, while having fun, and working hard at the same time.

## **Where I'm at and Where I'm going**

I'm currently taking CS50. I'm working on PSET 1. I have read the first three books of YDKJS. I may have to go back and reread those particular books. I will play catch up, but I do not mind out that at all. My math needs to be refreshed. I did complete calculus in high school, and I have gotten up to calculus in college. Going forward, I definitely want to kick up my learning and catch up, so I can participate in everything. Goal for this month is to get as much completed as I can.

## **My Commitments and Limitations**

My goal is to commit up to 20 hours per week. I do work a full time job as an QA. I will have days where I'm work late. Also, I'm getting married this year, but I do not feel that should not get in the way too much... I hope... ; )

## **What I bring**

I'm the type of person who works beyond what is required. I always look out for my fellow teammates/coworkers. I love helping others grow. I'm a bubbly individual that loves to have fun. Along with my personality, I bring my experience of working in the gaming industry for the last four years as QA. I always try to look outside the box, and I look to connect the dots where it shouldn't (I'm always trying to break software). 

## **Area of Interest**

My interest is learning the full end to end process of making a game. I want to understand all aspects of making a game with a emphasis on development. Art aspect of games intrigues me. I love to play Clash Royale, so I'm interested in recreating something close to it. 

## **Final Words**

While I'm at the beginning of the journey, I'm excited at the opportunity that is being offered here. If given the chance, I would love to help, grow, and build an awesome environment (even a gaming company ;). Thank you for all your hard work! You truly have changed lives.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
