### ISSUE TITLE
I would love to participate

### ISSUE THREAD

**Issue by RomchyFCC** [P1xt/games-development-signup#14]
# Who I Am
Hi everyone, my name is Roman Struna also known as Romchy in most of the www. I come from Slovenia and 2 months ago I quit my full time job to pursue a career in software development. I have been following P1xt's job ready guide, which I also intended to complete this month. I am very interested in game development and also plan to eventually end up there. 

### Where I'm At, and Where I'm Going
I have done 50%+ of the above mentioned guide, but went a bit off track to build a very solid development foundation. I am currently in process of deploying my personal portfolio website with my own domain name and excited to dive deep into react development.

As far as this project is concerned, I will have to play catch up with Functional Light JavaScript and Typescript, so this is where I will start next week when I am done with my current project.

### My Commitments & Limitations
This is very straight forward, I quit my job to pursue this career so I will be available all the time. I am very committed to this, which can be observed via my github profile page(I quit my job on 10th of Jan). 

In the 2 months I have been studying and developing I have dealt with serious personal issues but I still persevered and continued to build and learn. I am fairly confident nothing can stand in my way anymore.

# What I Bring
### Areas of Interest
Physics - this is by far my biggest interest. I want to build complex physics models such as black holes, bullet range/drops, the more complex the better. 
I want to explore physics that don't make sense in our world and would flip perception of a person playing the game or experiencing what I've built on their head.

### My goals as part of the team
Positive reinforcement, I've learned to be quite good at it and has become my daily routine. 
I try to selflessly help other who are going through what I had gone and I try to do it in a way that would also teach them. 
My friend and I started a small project where we try to teach new comers about the world of github and provide them a safe haven to test and learn about it and also ask questions.
I will bring this kind of attitude into the team if picked.

I do what needs to be done to meet a set deadline and to get the project done. I am also well aware that you can't just code double the next day if you skip one day so I never waste a day not coding.

## Final thoughts
As I write this issue, deprived of sleep because I couldn't contain my excitement, I hope to be welcomed into this team. I love meeting new people all around the globe and would be an honor to join a game developer team.
This is an amazing idea and even if I don't get drafted :D I wish you all the best in your endeavour!

Kind regards, 
Roman

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
