### ISSUE TITLE
Signing up!

### ISSUE THREAD

**Issue by Nedu** [P1xt/games-development-signup#15]
# **Who I Am**

Hello, everyone! My name is Nedu, and I have always been fascinated by game development and I am so glad that this opportunity is presenting itself which is why I am taking the plunge to learn and start building with everyone.

## **Where I'm At, and Where I'm Going**
Currently I am working through CS50 and the YDKJS books. I hope to be done with these by the end of March. I also hope to review some linear algebra and first year calculus as preparation. 

## **My Commitments & Limitations**
I can commit to working for an average of 10 hours a week to this group over the course of two years. However that number of hours could increase or decrease depending on how hectic my schedule is. My goal is to commit 20 hours a week. 

### **Areas of Interest**
My interests lie mostly in artificial intelligence and basically the general development that goes into game development. 

### **My goals as part of the team**
I will be supportive and helpful to other team members. I am open to learning and helping my other team members learn. I will work at this and be successful.
## **Final Words**
I'm so excited to begin on this journey with everyone and I am looking forward to learning and building great projects together

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
