### ISSUE TITLE
Sign me up!

### ISSUE THREAD

**Issue by Sc4ramouche** [P1xt/games-development-signup#16]
# Who I am

Hello everyone! My name is Vlad, I'm 22 years old student. Currently going through my first year of "Web technologies" master's degree at the university. My life has changed since I've discovered the world of programming, that caused me to become passionate learner. I'm totally fascinated with technologies. I've started to learn programming around one year ago and I was concerned about effective ways of learning. I've spent some time to organize myself and try different learning techniques that I'm glad to share with everyone, since they've made me more effective. But most importantly I'm really excited with opportunity to learn with a team of like-minded programmers and get better as a developer in a friendly crew. That's why I just couldn't pass by!

### Where I'm At, and Where I'm Going

I'm currently going through thrid book of YDKJS, my goal is to finish the series by the end of the March. I'm going to revisit CS50 and get familiar with TypeScript. I will start to read FLS as soon as I finish YDKJS.

### My Commitments & Limitations

My initial goal is to commit 2 hours daily to the course and probably more on weekends. I'm hoping to get a job as a junior JavaScript developer by the middle of the summer as I'm currently going through internship, but I know myself and I would strive to learn more about development outside of frontend field as well. 

### Areas of Interest

I love to tackle visible things (like animations) and I love video games, but I'm also concerned to understand how things work underneath the hood. I'm also looking in the direction of machine learning and I've taken it as a topic of my graduate work. I believe that studying underlying concepts and math make your mind more creative in problem solving and that's why I'm so passionate about learning new things.

### My goals as part of the team

I would like to share everything I know with others. I'm also thankful to ones who share their knowledge with me. I believe that there are no stupid questions and curiosity should thrive! I think that conversation can drastically improve learning for every participant, that's why I'm excited to learn in a team and take part in code reviews instead of isolating myself with dozens of books (books are vital, but you can learn so much from considering something from a different point of view!).

### Final Words

I'm excited by the opportunity to learn side by side with other inquisitive programmers. I believe that it could help every participant to grow and expand their capacities, because I consider game development as a field with a lot of interesting and complex things to tackle with. After all, I'm sure that it is great experience and truly rewarding journey!

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
