### ISSUE TITLE
let's make games!

### ISSUE THREAD

**Issue by iampeternguyen** [P1xt/games-development-signup#17]
# Who I Am

Hey everyone, my name is Peter. I got my bachelor's in Biology and Sociology and my master's in higher education. I'm Vietnamese-American and moved to Vietnam over 4 years ago. At first as a one year volunteer English teacher and then later I opened up my own little community center. Our goal is to empower people to think about the change they can create in their world (however they want to define that). I care a lot about social justice and want to create things that help people.

## Where I'm at, and where I'm going
I got into coding last year because I watched a video about an automated aquaponics system, and I thought I want to try to build that. I got started on FCC without knowing what a full stack developer was. I just figured if I enjoyed it, I would keep going, if not oh wells. I got into it really fast. Finished the front end cert in 3 weeks and discovered chingu. I read 5 of the YDKJS books, finished CS50 last November, did some [d3js/vuejs](http://killed-by-police-data.herokuapp.com/) stuff, and started working on python/django in February. I just finished my [medium clone](https://medium-clone-iampeternguyen.herokuapp.com/) today. I told myself when I got it done, I would fill out this application. 

Next, I'm going to read through the django docs a bit, and I want to get started with Phaser. 

## My Commitments & Limitations
I imagine I can commit to at least 10 hours a week to the group. Depending on the week I code anywhere from 10 to 30 hours. Some weeks I do miss though because I have to travel for another job I have. 

# What I Bring
## Areas of Interest
**AI/Machine Learning**
I got into python because I was curious about machine learning and AI. My interest was peaked during the python lesson of CS50. 

**Gamification**
A few years back, I read a book on gamification and I really enjoyed how it broke down an individual's motivation. It discussed how to apply game mechanics to real life. I would want to think more about that as I start to create my own things and why.

## Community building
I work for an iNGO right now and my goal is to coordinate a cohort of 10-15 American fellows working in Asia. I help create the structure of the community and help them troubleshoot problems with their local partners. I am also working on now helping partners develop their own culture around management and development of a fellow. I would also be interested in helping to build the community of this group as well. 

## Final Words
I'm excited to be part of a structured group. I've been looking at bootcamps recently because I wanted a feel for being with other people and being able to experience/share where we are along a similar journey. I think this group would definitely help me fill that desire.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
