### ISSUE TITLE
Signup!

### ISSUE THREAD

**Issue by rin-st** [P1xt/games-development-signup#18]
## Who I Am
Hello! My name is Rinat. I'm from Saint-Petersburg,  Russia. I’m 30. 
I work as a junior frontend developer for 5 months (fulltime). Also, I'm a math tutor (evenings and weekends), but I'll do it until June - I don't have time for it anymore.

## Where I'm At, and Where I'm Going
I began to learn web dev in January 2017, most of it on freecodecamp. Completed frontend certificate, first react and all API challenges. Finished mongo101js and almost finished the vue2 course on udemy.

I have read 4 and a half books ydkjs and watched 3-4 lections of CS50, but it was half a year ago. I will watch the course next 1-2 months. Currently, I participate in Chingu voyage 4 as a project manager of a tier-2 team. 

My plan for the month of March is to watch some CS 50 lectures, and maybe to read the second half of YDKJS Async & Performance book.

## My Commitments & Limitations
My goal is a commitment level around 10 hours until June (until Chingu voyage (20.04) and math tutoring ends), and 15-20+ hours per week after June.

### Areas of Interest

- Game design – setting, rules, content, maps design and so on
- Balancing – I love balanced games and I think balance is one of the main aspects of all great games
- Development

### My goals as part of the team
I have a math degree and I think it will help me a lot with math courses and algorithms and hope it will help to explain teammates things they don't understand.
I try to learn as fast as I can because I lost a lot of time in my 20’s – I will spend a huge part of my free time to this project.

## Final words
I play video games for 18 years and dream about developing games since I was 16. But life happens and I worked ten years in other areas (not IT). Super excited about this opportunity and about working with a team with the same goals!

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at #9 and start brainstorming names smile

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
