### ISSUE TITLE
First? :D

### ISSUE THREAD

**Issue by KamilCybulski** [P1xt/games-development-signup#2]
# Who am I
Hello, I'm Kamil. I'm 26 years old. I always had this thought that it would be cool to make games, but it never seemed like something achievable in a foreseeable future. The idea of going from zero to game dev hero in merely two years sounds like an amazing opportunity. 

# Where I am and Where I'm going
For the whole 2017 I've been working on the [comprehensive web-dev guide](https://github.com/P1xt/p1xt-guides/blob/master/wd-cs.md). I worked through CS50 and YDKJS and I have some familiarity with TypeScript. 

My plan for March is to read through Functional Light JavaScript and do some serious precalculus practice, so I can keep up with math courses.

# My Commitments & Limitations
I intend to commit as many hours as I need to complete all the course assignments and other tasks. Depending on my work it may not be split equally throughout the month.

# What I bring
## Areas of Interest 
I am mostly interested in the development aspect of the whole thing. I would also like to take a dive into AI, although I am not sure if I'll be able to provide much information to my teammates on this subject, considering that I would be starting from almost zero with this one.

## As a part of the team
I'll do my best to help others with my areas of interest.
I'll keep asking questions about other people's areas of interest.
I'll provide as much constructive feedback on other teammates work as I can.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
