### ISSUE TITLE
Too late?

### ISSUE THREAD

**Issue by tlcodes** [P1xt/games-development-signup#21]
# Who I am

Hello, I'm Thomas, I'm 35 and started learning to code about a year ago when I found P1xt's guides. I saw this game development opprtunity (maybe too late?) and would love to participate and continue learning at the same time.

# Where I am and Where I'm Going

I'm currently studying full time, I just finished the How To Code: Complex Data item on the https://github.com/P1xt/p1xt-guides/blob/master/wd-cs.md WD guide.
I started to learn TypeScript and need to go through Functional Light Javascript.

# Commitments & Limitations
I will dedicate at least 15 hours per week to the assignments of this course. My only limitation is I will only be available from April 15, leaving for about 2 week and having no access to Internet. After that I'll be entirely available to study and participate in this project. I'll totally understand if this absence is a red flag.

# What I bring

## Areas of Interest
In addition to the development / programming side, I'd like to dive into music making a little more. I played with some softwares in the past and found their open source alternative. I also like to read on psychology and worked as a digital marketer.

Video games were a big part of my life at a younger age and I feel this is something I'm missing. Being able to escape somewhere, be part of a story and have fun killing monsters.

## As part of the team
I'm willing to learn from others and help others progress too. I will share resources I believe can be helpful and be supportive. I won't be a "giant egocentric, bullying jackass".

**Comment by P1xt** [comment]
Not too late at all.

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.

**Comment by P1xt** [comment]
Signup abandoned? Message me if you're still interested.

**Comment by tlcodes** [comment]
@P1xt Hi, I'm still interested. As I said in my application I'll ont get access to internet fromage April 15. I'm having some wifi access just today and write this from my phone. Hop you can keep à seat for me :/

**Comment by P1xt** [comment]
Yep, just give a holler when you're back and we'll get you in.

**Comment by tlcodes** [comment]
@P1xt Hi, and thank you for your patience. Here's my holler: I'm back, let me in!

**Comment by P1xt** [comment]
Here's a link to sign into our slack - [Roundtable Interactive](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzQ3MDE0NTI3NjE3LWNkMGJiOGY1ZWE1MWJmNmMwMzA4MjU3MWQyNjE5NzIxZThhNTE5YzFlMjcyYWVjMGFlZTFkNmQ4NGMxOWRiNWE)
