### ISSUE TITLE
Interested

### ISSUE THREAD

**Issue by DarrenfJ** [P1xt/games-development-signup#22]
### Who am I
I'm just somebody who loves gaming. I got into the fCC stuff because ultimately I wanted to do games.

In my RL I do BA PM and QA for a software company. My background was Mech Engineering in robotics. Moved into Electronics cause I was into music (audio and radio. Basically built college radio stations for my 20's). fell into Process/Continuous Improvement and that ended me up in IT Project Management.

### Where I am and Where I'm going
I've done the fCC curriculum and working on the projects.. Interested in moving into the some of the P1xt guides as well..

### My Commitments & Limitations
Studying coding is my direction. MY limitations would be the full time job. But I code a bit every night. I'm on the 1000 day challenge ;)

### What I bring
Was an avid gamer. Total nerd. Sci-Fi geek. Totally obsessed with learning. had a challenge to do 30 Coursera courses and did about that many before they changed their format. One of my fav courses was the coursera equivalent of this ( https://www.ualberta.ca/admissions-programs/online-courses/understanding-video-games ) which is all about the non coding part of games. 

I can do QA, storyline junk. Vet ideas. 

### Areas of Interest
I love a good story. I also love something with  dark sense of humour.

### As a part of the team
QA, did some usability stuff as a BA. All around unassuming individual. More or less. prefer collaboration to going it alone, but also like to work alone sometimes to accomplish something.. when in the zone.

Love watching things become created from nothing.

### Next Steps
I like to help out and get whatever needs to be done, done.

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.

**Comment by P1xt** [comment]
Signup abandoned? Message me if you're still interested.

**Comment by DarrenfJ** [comment]
Still interested. Just got home from a weekend with family.. Sorry for late reply.

**Comment by P1xt** [comment]
No worries. I rather expected the holidays to take hold of a few folks through mid-week. Welcome to the group.

**Comment by DarrenfJ** [comment]
I'm in and reviewed everything last night.

Thanks for the invite!
