### ISSUE TITLE
Is this real life?

### ISSUE THREAD

**Issue by chris12540** [P1xt/games-development-signup#23]
# **Who I Am**
Hello 👋
My name is Christian and I'm 25. I started programming when I was 14 and have had a hunger for it since then. I aspire to be a video game developer because I love creating things for people to use. The fact that you can create a whole world for people to enjoy fascinates me to no end!

## **Where I'm At, and Where I'm Going**
I just found you tonight while looking through the FCC backend cert. I got curious and I'm glad I did since I found your guides! I would still be going through the front end program if I hadn't have found your job ready guide. Suffice to say that's where I am now, following your guide. This month I will be completing that guide and job searching. 

## **My Commitments & Limitations**
My goal is to commit to 20 hours a week. My only limitations are the time I will be investing in the job ready guide, interviews and eventually the full-time job. 

### **Areas of Interest**
Artificial Intelligence - I've always wondered why AI is something that has been so hard to capture and develop. I know that as a team we will not only learn but also make it better.

Level Design - I think level design is so fascinating in that it can make or break your title. At the same time if done correctly no one will ever notice. I believe in those little details when creating anything worth sharing. 

### **My goals as part of the team**
To be completely frank I have a lot of learning to do. However, I am willing to put the work, time and effort to the best of my ability. 

That said, I am coming back to programming after a year break of doing sales. The reason I am bringing this up is that during that time I got to work closely with the CEO who taught me some very enlightening ways to see life. I developed a positive mindset and I believe I can bring everything I have learned firsthand to the team. As everything in life, there are ups and downs, and it is during those down times that I believe I can serve as an adviser not only to individuals but to the team as a whole.

**Comment by P1xt** [comment]
Two questions:

**Comment by chris12540** [comment]
I promise to not be a jerk.

I have not finished it, I am enrolling today.

**Comment by P1xt** [comment]
Here's the [slack](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) we're all communicating on.

I'll get you an invite to the github organization.

You're in!
