### ISSUE TITLE
So keen.

### ISSUE THREAD

**Issue by pcb3** [P1xt/games-development-signup#24]
@P1xt 
Hi, I left a response on your medium article under pcb3. Any chance I can join or at least be part of the community?
I know it's very late but I really wanted to do games development and had started working independently on CS50.
I know a little javascript from FCC so I'm hoping it will come back to me during YDKJS and Functional Light JS. It will be a ton of work but I'm practically dedicating 30 hours a week to this. 
It's very hard going solo so would love the chance to work in a team of autodidacts.

A little about me:
I am from New Zealand and recently decided to switch careers and go back to college. Previously running a kitchen. I studied some math last year and started a crypto-related business. That took over and I decided to try give that a go instead of returning to uni this year. 
I put much hard work into the business and it's mostly running itself at this time, leaving me some hours in the week to learn a skill.

I have been an avid gamer since 7 years old. I feel like I could make a great game. All I need are the tools to make it happen. I believe this group could be the motivation and camaraderie that could help make it happen.

If it's too late I understand. I will continue on my own albeit slower pace. Really appreciate the time you've put into the guides. Unfortunately I'm often frozen by too many choices!

Thanks.

**Comment by P1xt** [comment]
@pcb3 Do you agree wholeheartedly to not be a jerk for the entire two years? :smile:

**Comment by pcb3** [comment]
@P1xt I wholeheartedly agree!
