### ISSUE TITLE
Sign Me Up!

### ISSUE THREAD

**Issue by kvie** [P1xt/games-development-signup#3]
## Who I Am

Hello, everyone! My name is Karyme, pronounced like Jeremy with a K. I'm a 24 year old student who has been interested in game development for quite some time, so this is an opportunity I can hardly pass up! I'd love to join this team to start learning and creating.

## Where I'm At, and Where I'm Going

In 2017, I made it halfway through PSET 4 of CS50. I took Introduction to Programming at my local college, focusing on the C++ language. I did do a good bit of JavaScript, but did not explicitly work through YDKJS, Functional-Light JS, or TypeScript.

My plan for the month of March is to quickly review the parts of CS50 I've already done and make as much new progress in the course as I can. I also intend to make some steady progress with YDKJS.

## My Commitments & Limitations

I can guarantee a minimum average of 10 hours a week to this group over the course of two years. My goal will be about 20 hours a week, but due to mental health, formal schooling, and possible upcoming employment, it will be difficult to guarantee that or more.

### Areas of Interest

My interests lie mostly in development (programming) but I consider myself to be an incredibly creative person. I will bring a well-rounded appreciation of the many aspects of game creation, but also an eagerness to learn from and support others.

### I am Friendly and Supportive

I am a very empathetic person, and I think that has a large impact on the morale of the group. I'm very accepting of others and along with my growing expertise in my areas of interest, I hope to bring smiles and a sense of camaraderie to this group. I'm a team player.

### I'd Like to Teach

At this point I don't have much experience teaching and tutoring others, but I have the intention to learn to help others. I'm excited about the opportunity to work hand in hand with others, supporting each other's growth.

## Final Words

I hope that between now and the start of this group, I will be able to demonstrate some of the progress I've made on the above promises. An incredible thank you to @P1xt for setting forth this project!

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
