### ISSUE TITLE
Signing Up

### ISSUE THREAD

**Issue by SharpEleven91** [P1xt/games-development-signup#5]
# Who I am
My names Cody, I'm 26 years old. I've been incredibly passionate about games since a young age. My earliest memory of video games is playing Battletoads. When I'm not coding or playing games I enjoy writing music.

# Where I am and Where I'm going
For the majority of 2017 I worked through the Computer Science / Web Development guide. I'm currently towards the end of the 2nd Tier. I've been kind of caught up in the Math parts as it's my weakest subject at the moment.

I have completed CS50, YDKJS (Would like to do a quick review, as it's been a few months). I have adequate knowledge of Typescript but have not used it extensively. I have not read FLJS but I have read Professor Frisby's guide on functional programming and will read FLJS this coming week.

# Commitments & Limitations

I can pledge at least 20 hours a week to the group. My current commitments give me a lot of free time and I'm very motivated to learn and become a better programmer / human being.

# What I Bring

I enjoy helping others. If I see an issue being discussed that I feel I have enough knowledge or experience with I will always try to help.

While I'm mostly interested in the programming aspect of game development. I am also interested in the areas of story design, music, and balancing.

I believe my constant struggle with Impostor syndrome doesn't allow me to bring any negativity to the team.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
