### ISSUE TITLE
signup

### ISSUE THREAD

**Issue by ksmai** [P1xt/games-development-signup#6]
# Who I am
Hi, I'm ksmai, 24 years old. As with everyone else I have always been interested in game development, but it is, at least as I see it, quite demanding and challenging so I have been hesitating to get into this area until I see this fascinating opportunity where there would be great mentors and peers to learn from and work with.

# Where I am and where I am going
In 2017 I worked on and completed the job ready guide (version 1), and continued my learning through the cs-wd guide. Currently I am mid-way through tier 2.

I have finished CS50, YDKJS and know a little bit of Typescript from coding Angular applications. I am going to finish the MIT Mathematics for Computer Science course soon and will start to read Functional Light Javascript and the Typescript doc afterwards.

# Commitment and Limitation
I can commit 20+ hours weekly, but they will mostly come from weekends and holidays.

# What I Bring
## Area of interest
I am most interested in machine learning and the underlying mathematics, but I also strive to be well-rounded in terms of different aspects of software development and a wide range of topics in computer science.

## As part of the team, I will
- share my knowledge and help the team to grow
- commit to meet every single one of the goals
- be friendly and helpful and work hard to solve problems together

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
