### ISSUE TITLE
My Signup

### ISSUE THREAD

**Issue by bernar83** [P1xt/games-development-signup#7]
# Who I Am
Hello! I'm bernar83 (or Adrian, whichever) and I'm a 24 yo student who has been studying web development in my journey to be a software engineer but always thought about getting into game development. Now that there's an opportunity to work with other great people (which I miss from working in Chingu) and to eventually make great games, I just couldn't pass up the chance. I would be very excited to be a part of this, to share my experience with others, and to be a better developer overall.

## Where I'm At, and Where I'm Going
I'm in school right now for software development. I took CS50 last year and read through YDKJS but it's always good to re-read them. My end goal is to be a software engineer in web but I always felt diving into other topics will make you better regardless and maybe by the end of these next two years I'll probably end up trying to be a game developer. 

My plan for the month of March is to read through functional light JS and learn more typescript.

## My Commitments & Limitations
My goal is a commitment level around 15 - 20 hours a week. It could be more or less depending on how I deal with a part time job but should be manageable. Regardless, I'll do my best to make up for any time I may miss from going out of town or if I have to study a little more for school.

# What I Bring
### Areas of Interest
My interests are mostly in programming, especially web development but I like to be well-rounded and like to learn about other things. I would provide a perspective from being a bit of a gamer myself, share a little knowledge of what I have about Javascript, and for these next two years I would like to get more into higher level math and AI or machine learning (which I will bring to the table as well).

### My goals as part of the team
I will be supportive and helpful. I'll try my best in my schedule to help figure out a problem with someone. I'll also try to give random funny emojis with puns to cheer everyone up when they're down.

I'm a team player. When I'm part of a group with a common goal I'll always do my best to make sure the team I'm on will reach that goal. 

I haven't blogged in awhile but I think I really like teaching through blog posts so whenever I feel there's info worth to teach in these next two years, I'll post them in our slack for everyone to read.

I hate bullies and jerks so you won't have to worry about that from me. Especially those jerk types in a gym setting. I REALLY don't like it. But that's a rant for another time haha.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.
