### ISSUE TITLE
This sounds so awesome!

### ISSUE THREAD

**Issue by LaurenDoughty** [P1xt/games-development-signup#8]
Who am I
Hi everyone, my name is Lauren. I'm 34, and I used to be a librarian. I decided computers were what I liked best about my old job, so I started a two-year programming curriculum at community college. I'm over halfway done with that. Now, I work in tech support. Getting into game development would be fantastic!

Where I am and Where I'm going
Currently, I'm a full-time student, but that's only for about another two months. After that, thanks to loading up on courses my first year, I'll be part-time instead. I enjoy my job in tech support, but I want to do something more fun. What could be more fun than designing games with a group of people all dedicated to making each other the best we all can be?
I'll need to brush up on all the prerequisites, and I'm committed to doing as much catch-up as I need to in order to contribute fully.

My Commitments & Limitations
I have about 20 hours of work and a variable amount of studying each week. However, my main course load will drop down to a part-time schedule this next semester.
If selected, I will put in however much time it takes to do my best.

What I bring
I am enthusiastic and always willing to try new things. I value constructive criticism. When the going gets tough, I keep pushing through until something is finished to the best of my ability. If I need help, I ask for it. I have a slightly off the wall sense of humor that I use at the drop of a hat. I'm endlessly curious about everything and not afraid to show it.

Areas of Interest
I want to develop RPG games that are different from "regular" RPGs. I'm not sure what different is yet. I used to play World of Warcraft, but stopped playing. I did not enjoy the game's "grind" or the nature of the questing. I would like to come up with something novel, interesting, and replayable.
I'm interested in learning whatever is involved to potentially do the above. Admittedly, I would be starting from ground zero on this.

As a part of the team
I am open to learning from everyone. Helping every member as much as I can is a definite priority. If someone else needs help, I point them at resources. I'm great at finding solid resources and helping people find their own answers. That was what I enjoyed the most about my work as a librarian.

**Comment by P1xt** [comment]
Hey there - I'm starting to think logistics (there will be plenty to setup, GitHub organization, Slack Group, etc) and it'd be quite helpful if everyone could take a quick look at https://github.com/P1xt/games-development-signup/issues/9 and start brainstorming names :smile:

**Comment by P1xt** [comment]
Please [click here](https://join.slack.com/t/roundtableinteractive/shared_invite/enQtMzM4MzU0NzQ2MjYxLTEyZTRjZWFkMTI2OWRiYjFiMjIyZjk4NDk1YjY1NWQ2YzkxMjRlZDI1ZjAxMDRiNWFiYThlNzQ4Y2ViMDVlN2Q) to join the group slack channel.

**Comment by P1xt** [comment]
Signup abandoned? Message me if you're still interested.
