### ISSUE TITLE
Need a team/group name

### ISSUE THREAD

**Issue by P1xt** [P1xt/games-development-signup#9]
I'll be setting up slack, etc over the next couple of weeks - and all that stuff needs a name (for the collective us).

Let's start the discussion here - maybe one idea per post so everyone can up vote and we can focus in on, say, the top 3, then put them up to a vote.

**Comment by kvie** [comment]
GemStorm

**Comment by bernar83** [comment]
We Type A Lot

**Comment by bernar83** [comment]
Broken Keyboards

**Comment by bernar83** [comment]
Mighty Typin Power Rangers

**Comment by razzlepdx** [comment]
Roundtable - makes me think of both teamwork and solo adventures.

**Comment by razzlepdx** [comment]
Collusion Games?  also collaborative, but slightly more sinister, haha.

**Comment by SharpEleven91** [comment]
Zero to Hero

**Comment by ksmai** [comment]
Arcane Bugs

**Comment by fiftyfivebells** [comment]
I'm really big into cryptozoology, so:

Team Sasquatch

But actually, I think Roundtable is my favorite so far.

**Comment by Sc4ramouche** [comment]
Pixeltable, as soon as there is nothing pefrectly round :smile:

**Comment by RomchyFCC** [comment]
New Moon
That will be my first attempt :)

**Comment by kvie** [comment]
Polyverse Games

**Comment by Nedu** [comment]
Legion Games?

**Comment by LaurenDoughty** [comment]
Roundtable Adventures - inspired by @razzlepdx Roundtable suggestion.

**Comment by najdhil86** [comment]
The Makers, Dev Heroes, 02Leaders just a couple of names I was thinking about.

**Comment by rin-st** [comment]
Perseverance
